### ISSUE TITLE
2023-06-30 fails to compile with uhdm-1.70

### ISSUE THREAD

**Issue by yurivict** [antmicro/yosys-systemverilog#1845]
```
/wrkdirs/usr/ports/cad/yosys-systemverilog/work/yosys-systemverilog-2023-06-30-eceb24b/yosys-f4pga-plugins/systemverilog-plugin/UhdmAst.cc:5095:33: error: too few arguments to function call, expected 2, have 1
        if (!object->Compare(obj)) {
             ~~~~~~~~~~~~~~~    ^
/usr/local/include/uhdm/BaseClass.h:174:19: note: 'Compare' declared here
  virtual int32_t Compare(const BaseClass* other,
                  ^
```

FreeBSD 13.2

**Comment by tgorochowik** [comment]
Thanks for the report!

This is expected, Surelog and UHDM are still under heavy development and new versions break all the time (sometimes the compilation like in this case sometimes it compiles and runs but produces a wrong result).

Use this repo (yosys-systemverilog) and the submodules in specific versions to ensure full compatibility (between the plugins, UHDM and Surelog).

In the meantime we are continuously working on having the latest versions, but it's not trivial due to the second type of the issues (i.e. compiles and runs, but produces incorrect netlists).
